[cli]
installer = "internal"

[model.llamacpp-Gemma-4-12B]
model = "Gemma-4-12B"
base_url = "http://127.0.0.1:8080/v1"
name = "Gemma-4-12B (Local)"
api_key = "llamacpp"
api_backend = "chat_completions"
context_window = 131072

[model.llamacpp-Qwen3.5-4B]
model = "Qwen3.5-4B"
base_url = "http://127.0.0.1:8080/v1"
name = "Qwen3.5-4B (Local)"
api_key = "llamacpp"
api_backend = "chat_completions"
context_window = 131072

[model.llamacpp-Qwen3.5-9B]
model = "Qwen3.5-9B"
base_url = "http://127.0.0.1:8080/v1"
name = "Qwen3.5-9B (Local)"
api_key = "llamacpp"
api_backend = "chat_completions"
context_window = 131072

[model.llamacpp-Qwen3.6-35B-A3B]
model = "Qwen3.6-35B-A3B"
base_url = "http://127.0.0.1:8080/v1"
name = "Qwen3.6-35B-A3B (Local)"
api_key = "llamacpp"
api_backend = "chat_completions"
context_window = 131072

[model.llamacpp-Bonzai-27B]
model = "Bonzai-27B"
base_url = "http://127.0.0.1:8080/v1"
name = "Bonzai-27B (Local)"
api_key = "llamacpp"
api_backend = "chat_completions"
context_window = 131072

[marketplace]
official_marketplace_auto_installed = true
default_skills_installs_purged = true

[[marketplace.sources]]
name = "xAI Official"
git = "https://github.com/xai-org/plugin-marketplace.git"

[models]
default = "llamacpp-Gemma-4-12B"

[ui]
max_thoughts_width = 120
fork_secondary_model = "grok-build"
yolo = false
compact_mode = false
